name: ToDWhitelist
author: Johan "Zephyyrr" Fogelstrom
main: com.talesofdertinia.ToDWhitelist.ToDWhitelist
version: 1.0
website: http://www.talesofdertinia.com
description: User Control Plugin for ToD.
database: true

commands:
  todwhitelist:
    usage: /todwhitelist ((whitelist|blacklist) (add|remove) <player> | backupmode (enable|disable))
    permission: todwhitelist.admin
    aliases: [wl,bl]

  invite:
    usage: /invite <playername> <e-mail>
    permision: todwhitelist.invite

permissions:
  todwhitelist.admin:
    description: Allows control of user access
    default: op
    children:
      usercontrol.whitelist: true
      usercontrol.blacklist: true

  todwhitelist.invite:
    description: Makes the invite system of ToDWhitelist to be used.
    default: false

